AWSTemplateFormatVersion: "2010-09-09"

Parameters:
  Environment:
    Type: String
    AllowedValues:
      - production
      - staging
      - develop
    Description: Environment Name.
  # DBSnapshotArn:
  #   Description: If you want to create an Aurora Cluster from your snapshot, please enter your Snapshot ARN. If you leave it empty, this template creates a brand new Aurora Cluster.
  #   Type: String
  SubnetIdList:
    Type: List<AWS::EC2::Subnet::Id>
    Description: Subnet Ids list for DataBase.
  DBClusterIdentifier:
    Type: String
    Description: The Database Cluster Identifier.
    Default: "efdb-cluster"
  PreferredBackupWindow:
    Type: String
  PreferredMaintenanceWindow:
    Type: String
  BackupRetentionPeriod:
    Type: Number
    MinValue: 1
    MaxValue: 35
  PubliclyAccessible:
    Type: String
    Default: false
    AllowedValues: [true, false]
    Description: Whether to enable the Publicly Accessibility.
  AutoMinorVersionUpgrade:
    Type: String
    Default: true
    AllowedValues: [true, false]
    Description: Whether to enable the Auto Minor Version Upgrade.
  EngineVersion:
    Type: String
  EnablePerformanceInsights:
    Default: false
    AllowedValues: [true, false]
    Type: String
  VpcName:
    Type: String
  TargetEnvNameSuffix:
    Type: String
  ProjectCategoryName:
    Type: String

Conditions:
  IsProduction: !Equals [!Ref Environment, "production"]

Mappings:
  RDS:
    develop:
      Instance1Name: kiralia-monitoring-api-db-01
      InstanceType: db.t4g.medium
    production:
      Instance1Name: kiralia-monitoring-api-db-01
      Instance2Name: kiralia-monitoring-api-db-02
      Instance3Name: kiralia-monitoring-api-db-03
      InstanceType: db.t4g.medium

Resources:
  AuroraCluster:
    Type: "AWS::RDS::DBCluster"
    Properties:
      BackupRetentionPeriod: !Ref BackupRetentionPeriod
      DatabaseName: "crossbird"
      DBClusterIdentifier: !Ref DBClusterIdentifier
      #VPCで作成したSGを使用
      DBClusterParameterGroupName: !Ref DBClusterParameterGroup
      DBSubnetGroupName: !Ref DBSubnetGroup
      Engine: "aurora-postgresql"
      EngineVersion: !Ref EngineVersion
      Port: 5432
      PreferredBackupWindow: !Ref PreferredBackupWindow
      PreferredMaintenanceWindow: !Ref PreferredMaintenanceWindow
      # SnapshotIdentifier: !Ref DBSnapshotArn
      StorageEncrypted: true
      MasterUsername: "{{resolve:secretsmanager:Kiralia/RDS:SecretString:username}}"
      MasterUserPassword: "{{resolve:secretsmanager:Kiralia/RDS:SecretString:password}}"
      Tags:
        - Key: Environment
          Value: !Ref Environment
        - Key: CostCenter
          Value: kiralia
      VpcSecurityGroupIds:
        - {
            "Fn::ImportValue": !Sub "${VpcName}${TargetEnvNameSuffix}-PostgreSQLDatabaseSG-ID",
          }
      EnableCloudwatchLogsExports: #ロググループへの保持期間設定は個別に実施
        - postgresql

  DBSubnetGroup:
    Type: "AWS::RDS::DBSubnetGroup"
    Properties:
      DBSubnetGroupDescription: "Subnet group for master"
      SubnetIds: !Ref SubnetIdList

  # CloudFormationのスタックアップデートを利用するためにDBInstanceIdentifierを指定しない。
  # Nameタグにより判別する（writer, readerはある時点での役割でしかないため、DBInstanceIdentifierやNameタグ自体に大きな意味はない）
  DBInstance01:
    Type: AWS::RDS::DBInstance
    Properties:
      Engine: aurora-postgresql
      DBClusterIdentifier: !Ref AuroraCluster
      DBInstanceClass: !FindInMap [RDS, !Ref "Environment", "InstanceType"]
      DBSubnetGroupName: !Ref "DBSubnetGroup"
      DBParameterGroupName: !Ref DBParameterGroup
      PubliclyAccessible: !Ref PubliclyAccessible
      AutoMinorVersionUpgrade: !Ref AutoMinorVersionUpgrade
      EnablePerformanceInsights: !Ref EnablePerformanceInsights
      Tags:
        - Key: Name
          Value: !FindInMap [RDS, !Ref "Environment", "Instance1Name"]
        - Key: Environment
          Value: !Ref Environment
        - Key: CostCenter
          Value: kiralia

  # DB Cluster Parameter Group
  DBClusterParameterGroup:
    Type: AWS::RDS::DBClusterParameterGroup
    Properties:
      Description: "RDS DB cluster parameter group for master"
      Family: aurora-postgresql15
      Parameters:
        client_encoding: UTF8
      Tags:
        - Key: Name
          Value: !Sub "${ProjectCategoryName}${TargetEnvNameSuffix}-db-cluster-param-group"

  # DB parameter group
  DBParameterGroup:
    Type: AWS::RDS::DBParameterGroup
    Properties:
      Description: "RDS DB parameter group the Aurora Cluster's instance(s)."
      Family: aurora-postgresql15
      Tags:
        - Key: Name
          Value: !Sub "${ProjectCategoryName}${TargetEnvNameSuffix}-db-param-group"

  PostgreSQLRDSSecret:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: Kiralia/RDS
      Description: "This secret has a dynamically generated secret password."
      GenerateSecretString:
        SecretStringTemplate: '{"username": "admin_kiralia"}'
        GenerateStringKey: "password"
        PasswordLength: 40
        ExcludeCharacters: '"@/\'
      Tags:
        - Key: CostCenter
          Value: Kiralia

Outputs:
  PostgreSQLDBEndpoint:
    Value: !GetAtt AuroraCluster.Endpoint.Address
    Description: "EndpointURL"
    Export:
      Name: !Sub PostgreSQLCluster-EndpointURL-${ProjectCategoryName}${TargetEnvNameSuffix}
